// Generate sun azimuth + elevation samples for a panel of Antarctic
// stations across austral-summer dates and a 24-hour cycle. Uses the
// project's existing Astropixels (JPL DE405) ephemeris for sun RA/Dec
// and the same GMST helper the runtime uses, so the output stays
// consistent with what the sim itself produces — useful as a fit
// target for the dome-caustic model.
//
// Output: js/data/antarcticSunSamples.js

import { writeFileSync } from 'node:fs';
import { sunEquatorial } from '../js/core/ephemerisAstropixels.js';
import { greenwichSiderealDeg } from '../js/core/ephemerisCommon.js';

const DEG = Math.PI / 180;

const STATIONS = [
  { id: 'mcmurdo',     name: 'McMurdo Station',         lat: -77.846,  lon:  166.668 },
  { id: 'south_pole',  name: 'Amundsen-Scott',          lat: -89.9975, lon:    0.0   },
  { id: 'concordia',   name: 'Concordia (Dome C)',      lat: -75.100,  lon:  123.330 },
  { id: 'vostok',      name: 'Vostok',                  lat: -78.464,  lon:  106.837 },
  { id: 'halley_vi',   name: 'Halley VI',               lat: -75.578,  lon:  -25.510 },
  { id: 'rothera',     name: 'Rothera',                 lat: -67.568,  lon:  -68.130 },
];

const DATES_UTC = [
  '2024-11-15',
  '2024-12-01',
  '2024-12-21',
  '2025-01-15',
  '2025-02-01',
  '2025-02-15',
];

const HOURS = [];
for (let h = 0; h < 24; h++) HOURS.push(h);

function altAzFromRADec({ ra, dec }, latDeg, lonDeg, gmstDeg) {
  const lstDeg = ((gmstDeg + lonDeg) % 360 + 360) % 360;
  const haDeg = ((lstDeg - (ra * 180 / Math.PI)) % 360 + 540) % 360 - 180;
  const ha = haDeg * DEG;
  const lat = latDeg * DEG;
  const sinAlt = Math.sin(lat) * Math.sin(dec) + Math.cos(lat) * Math.cos(dec) * Math.cos(ha);
  const altRad = Math.asin(Math.max(-1, Math.min(1, sinAlt)));
  const azY = -Math.cos(dec) * Math.sin(ha);
  const azX = Math.sin(dec) * Math.cos(lat) - Math.cos(dec) * Math.sin(lat) * Math.cos(ha);
  const azDeg = (Math.atan2(azY, azX) * 180 / Math.PI + 360) % 360;
  return { azDeg, altDeg: altRad * 180 / Math.PI };
}

function round3(x) { return Math.round(x * 1000) / 1000; }

const samples = [];
for (const dateStr of DATES_UTC) {
  for (const h of HOURS) {
    const date = new Date(`${dateStr}T${String(h).padStart(2, '0')}:00:00Z`);
    const eq = sunEquatorial(date);
    const gmstDeg = greenwichSiderealDeg(date);
    for (const st of STATIONS) {
      const { azDeg, altDeg } = altAzFromRADec(eq, st.lat, st.lon, gmstDeg);
      samples.push({
        stationId: st.id,
        utcISO: date.toISOString().replace(/\.\d+Z$/, 'Z'),
        az: round3(azDeg),
        el: round3(altDeg),
      });
    }
  }
}

const out = `// Auto-generated by scripts/build_antarctic_sun_samples.mjs — do not edit.
// Sun azimuth (deg, from north eastward) and elevation (deg, above
// horizon) for a panel of Antarctic stations across austral-summer
// dates, sampled hourly over 24 hours UT. RA / Dec drawn from
// Astropixels (JPL DE405) via the project's existing ephemeris;
// alt/az derived with the standard spherical-trig identities.

export const ANTARCTIC_SUN_SAMPLES = {
  meta: {
    source: 'Astropixels (JPL DE405) via js/core/ephemerisAstropixels.js + standard alt/az from RA/Dec/LST',
    generatedAt: '${new Date().toISOString()}',
    sampleCount: ${samples.length},
  },
  stations: ${JSON.stringify(STATIONS, null, 2)},
  dates: ${JSON.stringify(DATES_UTC)},
  samples: ${JSON.stringify(samples, null, 2)},
};
`;

const outPath = '/home/alan/claude/fe_model/js/data/antarcticSunSamples.js';
writeFileSync(outPath, out);
console.log(`Wrote ${outPath}`);
console.log(`  ${STATIONS.length} stations × ${DATES_UTC.length} dates × ${HOURS.length} hours = ${samples.length} samples`);
