// Scrape Fred Espenak's solar + lunar eclipse tables into a single JS
// data module. One-time script; rerun if the source pages change.
//
// Data source:
//   Fred Espenak, "Eclipses of the Sun / Moon"
//     https://www.astropixels.com/eclipses/solar.html
//     https://www.astropixels.com/eclipses/lunar.html
//   Both tables cover 2021 – 2040 and are derived from JPL DE405.
//
// Attribution baked into every consuming module; the runtime credits
// Fred Espenak + AstroPixels. No permission was sought beyond honouring
// the site's robots.txt (which allows all crawling).
//
// Output: js/data/astropixelsEclipses.js
// Shape: { solar: Eclipse[], lunar: Eclipse[] }
//   Eclipse = {
//     date: 'YYYY-MM-DD',
//     tdISO: 'YYYY-MM-DDTHH:MM:SSZ',  // Terrestrial Dynamical Time of greatest eclipse
//     utISO: 'YYYY-MM-DDTHH:MM:SSZ',  // UT (= TD − ΔT, ~69 s at modern dates)
//     type: 'Total' | 'Annular' | 'Partial' | 'Hybrid' | 'Penumbral',
//     saros: number,
//     magnitude: number,
//     duration: string | null,        // 'HHmMMs' for central eclipses, null for partial/penumbral
//   }

import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const CACHE = '/tmp/astropixels_cache';
mkdirSync(CACHE, { recursive: true });

async function fetchCached(url, path) {
  if (existsSync(path)) return readFileSync(path, 'utf8');
  const r = await fetch(url, { headers: { 'User-Agent': UA, 'Accept': 'text/html' } });
  const text = await r.text();
  writeFileSync(path, text);
  return text;
}

const MONTHS = { Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
                 Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11 };

// ΔT = TT − UT. At modern dates this is ~69 s. The sim's useful range
// (2021–2040) stays between 69 and 72 s; we approximate as constant.
const DELTA_T_SEC = 69.2;

function tdToUt(tdMs) { return new Date(tdMs - DELTA_T_SEC * 1000); }
function pad(n, w) { return String(n).padStart(w, '0'); }
function isoNoSecondsDec(d) {
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1, 2)}-${pad(d.getUTCDate(), 2)}`
       + `T${pad(d.getUTCHours(), 2)}:${pad(d.getUTCMinutes(), 2)}:${pad(d.getUTCSeconds(), 2)}Z`;
}

function stripHtml(html) {
  let s = html.replace(/<script[\s\S]*?<\/script>/gi, '')
              .replace(/<style[\s\S]*?<\/style>/gi, '')
              .replace(/<[^>]+>/g, ' ');
  s = s.replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&');
  return s.replace(/\s+/g, ' ');
}

// Solar table row:
//   2026 Aug 12  17:47:05  Total  126  1.039  02m18s  n N. America, w Africa…
function parseSolar(text) {
  const re = /(2[0-9]{3}) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{2})\s+(\d{2}):(\d{2}):(\d{2})\s+(Annular|Total|Partial|Hybrid)\s+(\d+)\s+([\d.]+)\s+(\d{2}m\d{2}s|-)/g;
  const out = [];
  let m;
  while ((m = re.exec(text))) {
    const [, y, monAbbr, dd, hh, mm, ss, type, saros, mag, dur] = m;
    const td = new Date(Date.UTC(+y, MONTHS[monAbbr], +dd, +hh, +mm, +ss));
    const ut = tdToUt(td.getTime());
    out.push({
      date: `${y}-${pad(MONTHS[monAbbr] + 1, 2)}-${dd}`,
      tdISO: isoNoSecondsDec(td),
      utISO: isoNoSecondsDec(ut),
      type, saros: +saros, magnitude: +mag,
      duration: dur === '-' ? null : dur,
    });
  }
  return out;
}

// Lunar table row:
//   2026 Aug 28  04:12:36  Partial  115  -0.885  0.932  …
function parseLunar(text) {
  const re = /(2[0-9]{3}) (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{2})\s+(\d{2}):(\d{2}):(\d{2})\s+(Total|Partial|Penumbral)\s+(\d+)/g;
  const out = [];
  let m;
  while ((m = re.exec(text))) {
    const [, y, monAbbr, dd, hh, mm, ss, type, saros] = m;
    const td = new Date(Date.UTC(+y, MONTHS[monAbbr], +dd, +hh, +mm, +ss));
    const ut = tdToUt(td.getTime());
    out.push({
      date: `${y}-${pad(MONTHS[monAbbr] + 1, 2)}-${dd}`,
      tdISO: isoNoSecondsDec(td),
      utISO: isoNoSecondsDec(ut),
      type, saros: +saros,
    });
  }
  return out;
}

async function main() {
  const solarHtml = await fetchCached('https://www.astropixels.com/eclipses/solar.html', `${CACHE}/eclipses_solar.html`);
  const lunarHtml = await fetchCached('https://www.astropixels.com/eclipses/lunar.html', `${CACHE}/eclipses_lunar.html`);

  const solarText = stripHtml(solarHtml);
  const lunarText = stripHtml(lunarHtml);
  const solar = parseSolar(solarText);
  const lunar = parseLunar(lunarText);

  console.log(`Parsed ${solar.length} solar + ${lunar.length} lunar = ${solar.length + lunar.length} events.`);

  const module = `// Auto-generated by scripts/scrape_eclipses.mjs — do not edit by hand.
// Data source: Fred Espenak, "AstroPixels — Eclipses of the Sun / Moon"
//   https://www.astropixels.com/eclipses/solar.html
//   https://www.astropixels.com/eclipses/lunar.html
// Both tables computed from JPL DE405 and cover 2021 – 2040.
//
// Attribution: all credit for the underlying ephemeris + eclipse
// canonicity belongs to Fred Espenak. This file is a parsed copy of
// Date, TD of greatest eclipse, type, Saros series (+ magnitude and
// central duration for solar) — only the columns the sim consumes.
//
// Shape per event:
//   { date: 'YYYY-MM-DD',
//     tdISO: 'YYYY-MM-DDTHH:MM:SSZ', // Terrestrial Dynamical Time
//     utISO: 'YYYY-MM-DDTHH:MM:SSZ', // UT (= TD − ΔT ≈ 69 s)
//     type:  'Total'|'Annular'|'Partial'|'Hybrid'|'Penumbral',
//     saros: number,
//     magnitude?: number,    // solar only
//     duration?: string|null // solar only; 'HHmMMs' for central,
//                            //             null for partial.
//   }

export const ASTROPIXELS_ECLIPSES = {
  meta: {
    source: 'Fred Espenak (AstroPixels) — https://www.astropixels.com/eclipses/',
    note:   'Computed from JPL DE405. ΔT approximated as 69.2 s (constant across 2021-2040).',
    generatedAt: '${new Date().toISOString()}',
  },
  solar: ${JSON.stringify(solar, null, 2)},
  lunar: ${JSON.stringify(lunar, null, 2)},
};
`;

  const out = '/home/alan/claude/fe_model/js/data/astropixelsEclipses.js';
  writeFileSync(out, module);
  console.log(`Wrote ${out} (${module.length} bytes)`);
}

main().catch(e => { console.error(e); process.exit(1); });
